[package]
name = "redis_mod"
version = "0.0.1"
authors = ["utsugi yuta <yutautsugi@outlook.com>"]
edition = "2018"
build = "build.rs"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
bitflags = "1.0"
libc = "0.2.0"
time = "0.1"

[build-dependencies]
cc = "1.0"

